name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: document-manager-idp/k8s-infrastructure
          token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}

      - name: Update image tag in auth-service manifest
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|business-logic:.*|business-logic:$IMAGE_TAG|g" business-logic/deployment.yaml

      - name: Commit and push changes
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add business-logic/deployment.yaml
          git commit -m "chore(business-logic): Update image tag to $IMAGE_TAG"
          git push origin main
